### ISSUE TITLE
Enforce to fill "Spent time" when submit a new note 

### ISSUE THREAD

**Issue by oldunclez** [ozguryazilimas/redmine_enforce_time_entry#2]
Hi 
Thank you for your plugin. What I want is as the following pic.
![image](https://user-images.githubusercontent.com/6986430/53147640-1d7b9f00-35e3-11e9-954a-b6c6f9c654cf.png)

What I done is : select all the status on "Previous Issue Status"
![image](https://user-images.githubusercontent.com/6986430/53147417-8282c500-35e2-11e9-8142-04a64f4f845f.png)

But whenever a user submit a new note , he is not  required to fill "Spent time".
Any idear? Thank you !

**Comment by sosogh** [comment]
edit subject

**Comment by zaburt** [comment]
Hi @sosogh, yes that is exactly what this plugin does. Two things that come to my mind

* plugin does not force users that has "Can Skip Log Time" permission and by default Admin users have this permission. Are you trying with an admin user ?
* Redmine has "Log Time" permission concept, if a user does not have this permission we do not force the user to enter spent time. Looking at the screenshot I suspect this is probably not the case here though.

**Comment by oldunclez** [comment]
@zaburt  Thank you for your hints,
Yes , I am trying with admin .
When I  try it with another user such as  "PM" , the "Previous Issue Status" and "New Issue Status"  works.
But "Only on Issue Status Changes" not work , i.e. when I change status from New to closed , I am not requred to fill the "Spent time" field .

Do I misunderstand something?

![image](https://user-images.githubusercontent.com/6986430/53157561-b8cd3e00-35fc-11e9-9b57-4b38391a13db.png)

**Comment by zaburt** [comment]
To force the user to enter spent time, you need to select at least one of the issue status. If the issue status changed from X to Y, the code will only force if the "Previous Issue Status" includes X, or "New Issue Status" includes Y.

"Only on Issue Status Changes" is check that let's you configure this scenario: an issue is already at status X, and there is an issue update but the status does not change, it is still X, "Only on Issue Status Changes" option decides if it should enforce spent time entry. Note that if X is not part of the "Previous Issue Status" or "New Issue Status", the code will not enforce spent time entry.

Does this help ?

Unfortunately this is a bit complicated but once you get used to it it gives a lot of flexbility. I think the documentation is not explaining this properly, I'll try to update it.

**Comment by oldunclez** [comment]
OK.  Thank you for your detailed explanation
